Feature/#33 feature friend api 차단 목록 조회 차단 설정
Match-Box-Team/BackEnd pull request #43
Opened 2023-04-17 13:20 UTC by cofls980

## ✅ 풀_리퀘스트 체크리스트

- [x] PR 제목: [Feature/Fix/Refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [x] commit message 가 적절한지 확인해주세요.
- [x] 적절한 branch 로 요청했는지 확인해주세요.
- [x] Assignees, Label 을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer 로 등록해주세요.
- [x] PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

<br/>

## 🔄 변경 사항 

friend api 2개 구현

- 차단 목록 조회
- 차단 설정

<br/>

## 📎 변경한 이유

- 

<br/>

closes: #33 

## 👨🏻‍💻 테스트 체크리스트

- 

<br/>

## 📌 변경 및 주의 사항

<br/>

2023-04-17 13:26 UTC, whaleshade commented on src/channels/events/channels.gateway.ts
> +      aa.channelId,
aa 변수명을 알아보기 쉽게 바꿔주세요

2023-04-17 13:26 UTC, whaleshade commented on src/channels/events/channels.gateway.ts
> +      aa.userId,
aa 변수명을 알아보기 쉽게 바꿔주세요

2023-04-17 13:27 UTC, whaleshade commented on src/channels/events/channels.gateway.ts
> +      aa.channelId,
여기도 변수명 바꿔주세요

2023-04-17 13:31 UTC, whaleshade requested changes
잘하셨습니당. aa 테스트용 변수명만 바꿔주세요

2023-04-17 15:57 UTC, cofls980 commented
추후에 다시 풀 리퉤스트 예정

2023-04-18 05:19 UTC, whaleshade approved these changes
넵 잘짜셨습니다.

2023-04-18 05:29 UTC, whaleshade reviewed
잘 하셨습니다! 전반적으로 userId와 buddyID를 같이 사용하여 테이블을 조회하고 있는데, friendID를 이용해 조회를 하는 로직으로 짜면 더 좋을것 같습니다.!

2023-04-18 05:45 UTC, whaleshade approved these changes
friendId 의 존재 이유에 대해 회의했던 내용을 깜빡하고 있었는데, 단순 식별자였다는 부분을 다시 상기하게 되었습니다만, 그럼에도 검증 단계가 필요하기 때문에 바로 friendId만 뽑아내어 적용한 부분이 좋은 것 같습니다!

2023-04-18 05:46 UTC, cofls980 commented
다음 pull request에서 friendID를 이용해 조회를 하는 로직으로 수정하여 올리겠습니다!

2023-04-18 05:46 UTC, merged